apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-manager
  namespace: REPLACE_ME
rules:
  - apiGroups: [""]
    resources: ["namespaces", "serviceaccounts", "services", "secrets"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: REPLACE_ME
subjects:
  - kind: ServiceAccount
    name: default
    namespace: git
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io
